
INSERT INTO USER(FIRST_NAME, PASSWORD, SURNAME, USERNAME) VALUES ('ivana','ivana','ivana','ivana');
INSERT INTO APARTMENT(HEATING, MUNICIPALITY, NUMBER_OF_BATHROOMS, NUMBER_OF_BEDROOMS, PARKING_SPOT,SIZE) VALUES ('OWN_HEATING','Karposh',1,1,true,54);
INSERT INTO AD(DESCRIPTION,EMAIL,NAME,PHONE_NUMBER,PRICE,PUBLISHED_ON,STATUS,SURNAME,APARTMENT_ID,AD_ID) VALUES ('Apparment in the center of the city','ivana.kochkovska@gmail.com','ivana','1111',250,'2019-06-26',true,'kochkovska',1,1);
INSERT INTO USER_AD(AD_ID,USER_ID) VALUES (1,1);
